import localFont from "next/font/local";
import NavBar from "@/app/components/NavBar"
import Footer from "./components/Footer";
import "./globals.css";
import Provider from "./Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavBar></NavBar>
            <main className="my-20">{children}</main>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
